app = "co-stream-website"
primary_region = "ord"

[build]
  dockerfile = "apps/ws/Dockerfile"

[http_service]
  internal_port = 4001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  WS_PORT = "4001"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
