app = "bridge-wild-meadow-5085"
primary_region = "ord"

[build]
  dockerfile = "apps/ws/Dockerfile"

[http_service]
  internal_port = 4001
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
